### ISSUE TITLE
production credentials should be managed via process.env

### ISSUE THREAD

**Issue by phra** [CTcue/ctAutocompletion#10]
hi,

as i can see [here](https://github.com/CTcue/ctAutocompletion/blob/master/config/config.js#L13) production credentials (host, port and api key) should not be checked in the codebase, **especially in a public repository**.

_attack scenario:_ if i am a competitor and i want to disrupt your operations i just can ddos (ip/tcp/http) your instance because i've the public IP of the production instance being used for the auto completion feature.

_solution:_ every kind of credentials should be managed via `process.env` in two ways:
- store non-sensitive development credentials in a .env file in the repository root and load them via [dotenv](https://github.com/motdotla/dotenv).
- store sensitive production credentials in a CD server that it will be responsible for production deploys. (of course, create an encrypted backup of them and put it in the right place)

plus point: git history can be used for fun and profit too. (e.g. [to recover removed credentials that were once checked in](https://github.com/CTcue/ctAutocompletion/blob/db4a3a2bda8309a0a2d8139c2cdd162ba80fa9e9/config/config.js#L18))

**Comment by Tessmore** [comment]
Good point! I did a quick history sweep, I guess github still keeps the files online. You're right though :)

(It's not actually our IP address, nor do we use MySQL. I guess it's some artifacts from an old app setting, ah well)
